name: Build DocFX Documentation

on:
  push:
    branches:
      - main

permissions:
  actions: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.DOCFX_SECRET }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Install DocFX Tool
      run: dotnet tool update -g docfx

    - name: Add .NET Tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Build Documentation with DocFX
      run: docfx docfx/docfx.json

    # - name: Create new folder
      # run: |
        # mkdir -p test
        # touch test/.gitkeep
        # git config --global user.email "stocker.leonhard@gmail.com"
        # git config --global user.name "LS"
        # git add test/.gitkeep
        # git commit -m "Add 'test' folder with .gitkeep"
        # git push https://${{ secrets.DOCFX_SECRET }}@github.com/Deputy-Chief-Hardy/docfx-testproject.git HEAD:${GITHUB_REF#refs/heads/}
